### ISSUE TITLE
Clean up setting of options in dynare_sensitivity.m

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1016]
Currently, it is very intransparent and prone to bugs. 
-  `neighborhood_width` forces 

```
if options_gsa.neighborhood_width,
    options_gsa.pprior=0;
    options_gsa.ppost=0;
end
```

but the manual says that  `neighborhood_width` only works when `pprior=0` and `ppost=0`. This seems like a bug. If we reset options set by the user, we should consistently provide warnings on the screen. 
- Even more problematic, without any indication in the manual, using `morris=1` overwrites almost all other user-specified options:

```
if options_gsa.morris==1,
    if ~options_gsa.identification,
        options_gsa.redform=1;
    end
    options_gsa.pprior=1;
    options_gsa.ppost=0;
    %options_gsa.stab=1;
    options_gsa.glue=0;
    options_gsa.rmse=0;
    options_gsa.load_rmse=0;
    options_gsa.alpha2_stab=1;
    options_gsa.ksstat=1;
    options_gsa.pvalue_ks=0;
    options_gsa.pvalue_corr=0;
    OutputDirectoryName = CheckPath('gsa/screen',M_.dname);
else
    OutputDirectoryName = CheckPath('gsa',M_.dname);
end
```

In particular, that results in none of the user-requested output being displayed. See http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=7115. @rattoma Is there a particular reason for this? I could not find any apparent incompatibility of `morris=1` with e.g. posterior sampling.

**Comment by rattoma** [comment]
@JohannesPfeifer 
On point 1 [neighborhood_width]: I agree to put a warning.

On point 2: Morris sampling method is not well suited for performing Monte Carlo filtering tests, which are in fact triggered by rmse. 
Indeed it would be interesting to provide Morris measures associated to rmse's, but since these are not implemented, then better just to skip that kind of analysis. 
So, the idea is that Morris must be associated either to reduced form mapping or to identification. In the first case (the default) sensitivity analysis is performed in entries in state space matrices, while in the second case this is done for variance decomposition of observables, theoretical moments of observables and state space matrices. 
Concerning posterior sampling, morris needs independent distributions in parameters, so it is not suited for posterior sampling.

**Comment by JohannesPfeifer** [comment]
@rattoma Generally, if there is an incompatibility between options, I would always provide an error, but never override user settings.

**Comment by rattoma** [comment]
@JohannesPfeifer OK. will do

**Comment by rattoma** [comment]
I should have fixed this in my last PR

**Comment by JohannesPfeifer** [comment]
@rattoma #1388 provides error messages for incompatible settings, but keeps the critical parts outlined above inteh file. Can it be that these statements can now never be reached?

**Comment by rattoma** [comment]
@JohannesPfeifer the critical statements can be reached if the user leaves GSA to its default. Then, sensitivity default options need to be re-set with Morris. So such statements need to be there to fix default behavior.

In the traps I only check options EXPLICITLY set by the user.

**Comment by JohannesPfeifer** [comment]
@rattoma Perfect. Good to know. Thanks for the clarification.
