### ISSUE TITLE
fix test suite on OS X

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#1072]

**Comment by stepan-a** [comment]
The problem is the default startup folder of Matlab. For the testsuite to run smoothly Matlab must start in ```dynare/tests``` and not in another directory (in my case the default startup folder was my home directory, as a consequence Matlab failed in finding the ```run_matlab_test```). I resolved this issue by changing the configuration of Matlab. See the documentation [here](http://fr.mathworks.com/help/matlab/matlab_env/matlab-startup-folder.html). Alternatively we could change the rule for ```m.trs``` in ```Makefile.am```, but as this issue does not show up in Linux I did not change ```Makefile.am```.
