### ISSUE TITLE
Account for MAC in AnalyseComputationalEnvironment.m and GiveCPUnumber.m

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1272]
The call to 
`[si0 de0]=system('grep processor /proc/cpuinfo');`
should be
`[si0 de0]=system('sysctl -a | grep machdep.cpu | grep core_count');` (see http://fortysomethinggeek.blogspot.de/2012/11/getting-cpu-info-from-command-line-in.html)

`GiveCPUnumber.m` then also needs to be adjusted to account for this.

Related to #838

**Comment by houtanb** [comment]
@JohannesPfeifer does this need to be a separate issue or can we just include it as a comment in #838 ?

**Comment by JohannesPfeifer** [comment]
@houtanb I wasn't sure how encompassing #838 is, because it relates to a particular file that hangs up. This ticket here points to a more general issue that MAC and Linux are not always the same and may require a different treatment. But feel free to append this to #838 and close this ticket.

**Comment by houtanb** [comment]
@JohannesPfeifer I'm going to add this to that because parallel doesn't account for OS X at all. The `Environment` variable is based on whether the computer is or is not a pc. Hence, that will have to be changed even to fix this bug and changes will have to be made throughout the code. I'll mark this as a duplicate and put a reference there to this ticket.
