### ISSUE TITLE
introduce posterior_nograph option

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#1356]
I think it would be useful to have an option like:

`options_.posterior_nograph`

with default value at 0 like standard nograph. 

This option would allow performing all possible posterior subdraws for irfs, smoothed variables etc, but avoiding to produce thousands of useless graphs that are currently done [for large models at least]. 

I think it would also be useful to make a distinction w.r.t. `options_.nograph` since the latter would not trigger prior/posterior plots of parameter estimates which would be required in any case. 

And by the way, `pm3` and `posterior_irf` do not seem to honor the nograph option: plots are made in any case. So at least we should make sure `nograph` would work properly?

If you agree, I would make the appropriate changes to the matlab `pm3` and `posterior_irf` routines with `posterior_nograph` [the preprocessor could be updated with this extra option, then].

**Comment by JohannesPfeifer** [comment]
@rattoma I agree in principle, But I would go for a more nested approach in `options_`, with something like `options_.no_graph.posterior` where `options_.no_graph` takes up `nograph` options for various commands. We should then alter `options_.shock_decomp.nograph` to `options_.no_graph.shock_decomp`. 
The remaining problem is how to link the general `nograph` option to the specific ones. I guess it is not feasible to have `nograph` reset the fields in `options_.no_graph` to 0, because then the user cannot easily undo this choice. Therefore, proper checks will always be something like
```if ~options_.nograph && ~options_.no_graph.posterior```

**Comment by rattoma** [comment]
It seems your suggestion should work. Most of (maybe all?) the current `nograph` checks will remain unaltered, since `posteriorIRF` and `prior_posterior_statistics` currently do not honor `nograph` and we can upgrade the check for `shock_decomposition`.

**Comment by JohannesPfeifer** [comment]
@rattoma Yes. In #1358 I did the preprocessor interface and the `shock_decomposition` part. You only need to do the part related to `pm3` and `posterior_irf`

**Comment by rattoma** [comment]
@JohannesPfeifer many thanks
