### ISSUE TITLE
Decide on treatment of qz_criterium in estimation with particle filter

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1377]
Currently, if a unit root is present, estimation with `order=2` will result in an error. Using `diffuse_filter` will disable the check, but obviously makes no sense for particle filtering. See http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=13126

**Comment by JohannesPfeifer** [comment]
@stepan-a Any thoughts on this?

**Comment by stepan-a** [comment]
@JohannesPfeifer  Unit roots are problematic because of the initial condition of the filter. In the case of a nonlinear filter we use by default the ergodic distribution of the states (which is not definite in presence of a unit root). But other initialisation are available. For instance we can initialize the filter with a diagonal covariance matrix or a covariance matrix estimated with a stochastic simulation of the model at second order (which would not help in this case, because the simulated variances should increase linearly with the size of the simulated sample). For now, I guess that the only solution is to use the ad-hoc diagonal covariance matrix in this case. I need to test this and discuss the problem with @FredericKarame.

**Comment by JohannesPfeifer** [comment]
@stepan-a @FredericKarame Then I would go for a more informative error message for now and deal with this once people start requesting this feature more.
