### ISSUE TITLE
Add interface for flexible IRF-generation

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1531]
Create block
```
generate_irfs(options_list);
(groupname1), exo_name1=1, exo_name 2=-0.5;
(groupname2), exo_name1=2, exo_name 3=-0.5;
end;
```
or alternatively (as suggested in #115 )
```
generate_irfs(options_list);
[ name='groupname1' ] exo_name1=1, exo_name 2=-0.5;
[ name='groupname1' ] exo_name1=2, exo_name 3=-0.5;
end;
```
where `options_list` can be (for now)
- `stderr_multiples` translating to `options_.irf_opt.stderr_multiples`
- `diagonal_only` translating to `options_.irf_opt.diagonal_only`

and where each line translates into 
1. a cell array `options_.irf_opt.irf_shock_graphtitles` storing the group_name along the rows 
2. a column of a matrix `options_.irf_opt.irf_shocks` of size M_.exo_nbr*n_lines where non-specified `var_exo` get a 0 entry.

If no line is provided, leave those fields empty.

The block translates into
1. setting of options_
2. a call to `oo_.irfs=generate_irfs(M_,options_,oo_)`

**Comment by stepan-a** [comment]
I prefer the first option.

**Comment by stepan-a** [comment]
@JohannesPfeifer Before the call to `generate_irfs`, should we not first compute the steady state and the reduced form solution? Otherwise it means that the command must follow the `stoch_simul` command and that if a user decides to change the value of a parameter between `stoch_simul`  and `generate_irfs` (or calls more than once  `generate_irfs` for different calibrations) the new parameter value will not be honored.

**Comment by houtanb** [comment]
The syntax should allow from `1` to `N` exogenous variables to be set per line
