### ISSUE TITLE
dataset_ is a dseries and no longer a structure

### ISSUE THREAD

**Issue by thomasbrand** [DynareTeam/dynare#1544]
The last commits about `dseries` (between October 10th and October 14th) modified the type of the `dataset_` output in `results.mat`. It was previously a matlab structure, and now it is a `dseries`. The consequence is important (for me) because now I need Dynare to read the `dataset_` output. 

Was it on purpose or do you think you will go back to a structure ?

Thank you.

**Comment by stepan-a** [comment]
I think this is a consequence of the move to the new class interface. When an object is loaded and that the class definition is not in the path, the object is no more automatically converted to a structure. This issue only affects people which do not have dynare in the matlab's path (I suppose this is your problem since you load the mat file from R). I will push a method to convert `dseries` objects to a structure. You can use it in the mod file to convert `dataset_` and save it in a `mat` file.

**Comment by stepan-a** [comment]
@thomasbrand I have just updated the `dseries` submodule in the master branch with a new function `struct`. All you have to do in the mod file (after the `estimation` command) is:

```matlab
dataset__ = struct(dataset_); % Converts the dsseries object to a matlab's structure.
save mydata.mat dataset__;  % Saves the structure in a mat file which can be loaded later. 
```
