### ISSUE TITLE
allow length operator in macroprocessor to return the length of strings

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1547]
At present, the length operator applied to a string always returns 1.

It would be good if it returned the length of the string.

Try e.g.:

```
@#define Numbers = [ "1", "2", "3", "4", "5", "6" ]
@#define TestString = "Hello"
@#echo Numbers[ length( TestString ) ]

parameters a;
a = 1;
```

Incidentally, it would be good if there was a number to string function in the pre-processor!

**Comment by houtanb** [comment]
NB: The length operator only works on arrays, so this is correct. What @tholden is asking is that it also work on strings.

**Comment by tholden** [comment]
Hmm. I don't see any situation in which it makes sense to return 1 as the length of a string. Either the length operator should return an error when evaluated on a string, or it should behave sensibly. Returning 1 without an error seems like a bug.

**Comment by JohannesPfeifer** [comment]
I agree with @tholden A string is an array of characters. So its length is not 1 unless it is just a single character

**Comment by houtanb** [comment]
@JohannesPfeifer for the macro-processor a string is a string, not an array of characters as in Matlab. The `length` operator only works on arrays, as you can see from the manual, pg 136.

As far as the macro-processor is concerned, the string is converted to an array, hence 
```
@#echo Numbers[ length( TestString ) ]
```
becomes
```
@#echo Numbers[ length( [TestString] ) ]
```
returns `1` because this is an array with one element in it. At the moment, the only change I can make is to modify the manual to make this clear.

@tholden to have the change you request anytime in the foreseeable future, there are two options:

1. You can do it yourself and submit a pull request. This way would probably be iterative with you making some changes, me telling you how to correct them until the commit was in good shape.

1. You or your institution could provide financing to the Dynare project to have this implemented. If you would like to discuss financing we can do that via email with @stepan-a

**Comment by svillemot** [comment]
Reopening, actually it makes sense to have `length` return the length of a string, since there is an indexing operator for strings.

**Comment by svillemot** [comment]
@tholden This has been fixed in Dynare 4.5.6 (just released). The length operator on a string now returns the number of characters.

**Comment by stepan-a** [comment]
Actually 4.5.6 will be released tomorrow.

**Comment by tholden** [comment]
Thanks again.
