### ISSUE TITLE
octave option requires -std-c++14

### ISSUE THREAD

**Issue by yurivict** [DynareTeam/dynare#1599]
dynare fails to build without -std-c++14 now after octave update.

Found in the FreeBSD port.

**Comment by svillemot** [comment]
Dear @yurivict,

Are you referring to the FreeBSD package there: https://www.freshports.org/math/dynare/ ?

If yes, then this is a problem with the packaging, and you should report it at freshports.org. We the Dynare Team have no way to fix the FreeBSD port.

Best,

**Comment by yurivict** [comment]
> If yes, then this is a problem with the packaging

You are wrong. Callers shouldn't be expected to guess and pass the right --std=c++NN flag. I don't really know what C++ standard is supposed to be used in your code. This is why you should add this line to the project.

You probably use gcc, and it doesn't ask for such flags, but FreeBSD uses clang, and clang requires this flag to be set.

**Comment by svillemot** [comment]
Can you then please give more details about the issue?
Is it in the preprocessor or in the MEX files for Octave? (I guess the latter, because the preprocessor is currently in C++03, though we will soon upgrade to C++14).
Concerning the MEX files for Octave, those are also written in C++03, and we get our CXXFLAGS for `mkoctfile`. So I don't see how `-std=c++14` could be required, unless it is used in headers from Octave, in which case it's `mkoctfile` that should set the flags (and, as I said before, it would be a packaging issue of Octave in FreeBSD ports).

**Comment by svillemot** [comment]
Also note that for the time being we only support Octave 4.2. We haven't yet tested Octave 4.4.

**Comment by yurivict** [comment]
It breaks with these messages:
```
/usr/local/include/octave-4.4.0/octave/dim-vector.h:200:21: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
  template <typename... Ints>
                    ^
/usr/local/include/octave-4.4.0/octave/dim-vector.h:204:10: error: no member named 'initializer_list' in namespace 'std'
    std::initializer_list<octave_idx_type> all_lengths = {r, c, lengths...};
    ~~~~~^
/usr/local/include/octave-4.4.0/octave/dim-vector.h:204:27: error: unexpected type name 'octave_idx_type': expected expression
    std::initializer_list<octave_idx_type> all_lengths = {r, c, lengths...};
                          ^
/usr/local/include/octave-4.4.0/octave/dim-vector.h:204:44: error: use of undeclared identifier 'all_lengths'
    std::initializer_list<octave_idx_type> all_lengths = {r, c, lengths...};
                                           ^
/usr/local/include/octave-4.4.0/octave/dim-vector.h:204:58: error: expected expression
    std::initializer_list<octave_idx_type> all_lengths = {r, c, lengths...};
                                                         ^
/usr/local/include/octave-4.4.0/octave/dim-vector.h:205:33: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (const octave_idx_type l: all_lengths)
                                ^
/usr/local/include/octave-4.4.0/octave/dim-vector.h:205:35: error: use of undeclared identifier 'all_lengths'
    for (const octave_idx_type l: all_lengths)
...etc...
```

Clang compiler is used.
It only breaks when the octave option is selected.
Octave 4.4.0 is used, OS is FreeBSD 11.1
The reason I reported this is that I discovered this problem while committing the update to the dynare port.
I don't think this is a huge issue, just a small problem.
Ports shouldn't be required to supply extra flags like this.

IMO, you should just add this flag ```--std=c++14``` when octave option is selected, this would be a good solution.

**Comment by svillemot** [comment]
As you can see, the C++11/C++14 code is in Octave headers. And Dynare gets its `CXX` and  `CXXFLAGS` from `mkoctfile`, which is the tool used to build MEX/Oct extensions.

Basically your problem shows that `mkoctfile` is probably broken under FreeBSD ports. Nothing to do with Dynare. I'm therefore closing this issue.

Thanks for maintaining the Dynare package for FreeBSD !

**Comment by svillemot** [comment]
Just some extra technical details to help you debugging this.

You can see the compiler and flags picked by Dynare when compiling Octave extensions in `mex/build/octave/configure.ac`:
```
CXX=`$MKOCTFILE -p CXX`
CXXFLAGS=`$MKOCTFILE -p CXXFLAGS`
```
(where `MKOCTFILE=mkoctfile`).

`mkoctfile` is the command-line tool for compiling Oct and MEX extensions (i.e. commands written in C or C++ and callable directly from the Octave command line). This is precisely what we are doing in the Octave build system (but instead of calling `mkoctfile` directly, we are extracting the flags from it, because we need more flexibility).

This technique works on all GNU/Linux distributions that we have tested, on Windows and on some OS X ports.

Is it possible that your version of Octave was compiled with GCC instead of Clang? This could explain why `mkoctfile` does not give the `-std=c++14` flag.

**Comment by svillemot** [comment]
Or could it be that you have two Octave installations on your machine, and that the `mkoctfile` that is in the `$PATH` does not correspond to the Octave installed under `/usr/local/` ?
