### ISSUE TITLE
Fix bug in mjdgges.mex

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1609]
See email from 04/22/18.
```[err, ss, tt, w, sdim, dr.eigval, info1] = mjdgges(E, D, DynareOptions.qz_criterium, DynareOptions.qz_zero_threshold);```
returns ```sdim=6.``` However, manually computing `sdim` based on the returned `dr.eigval` via
```
sum(abs(dr.eigval) < DynareOptions.qz_criterium)
```
returns 8.

**Comment by MichelJuillard** [comment]
It turns out that when there are eigenvalues very close to qz_criterium sdim may be different from 
```
sum(abs(dr.eigval) < DynareOptions.qz_criterium)
```
because it is faster to use ``sdim`` rather than to compute ``sum(abs(dr.eigval))``, I suggest that we rely only on ``sdim``as we do now for ``stoch_simul``
However, we use ``sum(abs(dr.eigval))`` for ``check``. I suggest that we add ``sdmin`` as an element of ``oo_.dr.`` and that ``check `` use ``oo_.dr.sdmin`` so as to always return the same diagnostic than stoch_simul.
In the documentation, we should indicate that ``stoch_simul`` and ``check`` may return diagnostics different from what would suggest ``sum(abs(oo_.dr.eigval))`` when eigenvalues are very close to ``qz_criterium``

**Comment by stepan-a** [comment]
Done in 8f53be2a6fe819175e8d992fb7e8fe24e99f8e68.
