### ISSUE TITLE
support mcmc_* options wherever there's an mh_* option

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#644]
as mcmc is more general than mh. support mh_* for backwards compatibility.

**Comment by JohannesPfeifer** [comment]
Decision: integrate the option into `posterior_sampling_options` so that no prefix is used, e.g. it would simply be `nblocks`

**Comment by houtanb** [comment]
@JohannesPfeifer is there a ticket for that?

**Comment by JohannesPfeifer** [comment]
@houtanb No, there isn't. And I am not sure, we should actually duplicate existing options. Users are used to particular options with the `mh_`-prefix. Therefore I would not also introduce the same option with the `mcmc_`-prefix. For new options related to other samplers, we do not need a prefix at all due to the `posterior_sampler_options`-construct.
