### ISSUE TITLE
rename hessian.m in dyn_hessian.m

### ISSUE THREAD

**Issue by MichelJuillard** [DynareTeam/dynare#667]
In order to avoid name collision with other Matlab program/toolboxe

**Comment by JohannesPfeifer** [comment]
@stepan-a Your suggestion only works if you are the Stackelberg leader. When every toolbox requires to be on top of the path, they become incompatible. For that reason, I would like to rename both ```hessian.m``` and ```irf.m```. Particularly the latter is known to cause issues with LeSage's toolbox as evidenced by numerous posts in the forum.

**Comment by stepan-a** [comment]
Ok. I fixed this in commit 0e1dd779b953971bcdc4b7318bb0ff1d48eff528. Dynare automatically (and temporarily for the current matlab session) change the path if needed (e.g. if Dynare's routines are overriden by routines provided by other toolboxes). I checked with Le Sage's toolbox.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I think we can regard this issue as closed then?

**Comment by MichelJuillard** [comment]
@stepan-a, doesn't your solution assume that the user doesn't use Le Sage toolbox in her *.mod file?

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Implicitly, is does. The Dynare routine will always have precedence as it is higher in the path.

**Comment by MichelJuillard** [comment]
I would prefer to rename our functions when we learn that their is a conflict. I think that we want to give users the maximum flexibility in using other tools with Dynare.

**Comment by stepan-a** [comment]
I still do not agree with this solution. The original problem with ```hessian.m``` reported by Andrea a year ago was that his ```dynare/matlab``` folder was not on top of the matlab's path, and that dynare was calling the wrong version of ```hessian.m```. This kind of problem is addressed by 0e1dd779b953971bcdc4b7318bb0ff1d48eff528. 

@MichelJuillard imagines another situation, which to my knowledge was never reported, where a user needs to call another version of hessian routine (I do not know why, but I suppose that this for doing stuff not implemented in dynare). I do not perceive the flexibility issue here... The user is not jailed, (s)he can perfectly name his(her) hessian routine ```notdyn_hessian.m```... Or temporarily change the matlab's path. My point is that this is a never ending strategy, and that we could already jump to the conclusion that we should prefix all our routines with ```dyn_``` (a safer prefix choice would be ```Fva5LFPO2poO1kX_``` because nobody would want this one ;-).

It is not hard to find matlab codes or libraries with ```check.m``` or ```steady.m``` routines. Should we already prefix them? To my knowledge, nobody complained about these *conflict*s... As for ```hessian.m```.

We could solve this issue using the namespace capability of matlab... But this is not implemented in Octave 3.8. I do not know if this will come with the next version (I understood that this is related to the new class interface).

**Comment by JohannesPfeifer** [comment]
@MichelJuillard After a few months with 0e1dd77 I think the new path management is successful in preventing the described problems. Thus, I agree with @stepan-a and would propose closing the ticket.
