### ISSUE TITLE
relative_irf

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#720]
Would it make sense to allow option relative_irf also in estimation for producing bayesian irfs?
Would it be possible to allow options to the new syntax
`irf_calibration(<options>)`

in particular would be fine to have the relative_irf option

`irf_calibration(relative_irf)`

**Comment by JohannesPfeifer** [comment]
@rattoma #740 introduced ```relative_irf``` to estimation. Is there anything else required for closing this ticket?

**Comment by rattoma** [comment]
if is also available in `irf_calibration` ?

**Comment by JohannesPfeifer** [comment]
No. @houtanb This now seems to be a preprocessor issue. What is still needed is allowing the ```irf_calibration```-block to have the input argument ```relative_irf``` (mapping to ```options_.relative_irf```) similar to the way the ```use_calibration``` option is passed to the ```estimated_params_init``` block. 
@rattoma I have one additional question after looking up this block: it seems the option is specific to the moment computation, but it will generally affect the IRF display of ```stoch_simul``` and ```estimation```, even if these IRFs are not restricted. Is this intended?

**Comment by rattoma** [comment]
I am not sure to understand your question. Shouldn't `relative_IRF` only apply for `irf_calibration` and be irrelevant for moment computation?

**Comment by JohannesPfeifer** [comment]
@rattoma You are right that this option will not affect computations. I missphrased. What I meant is the following. Say you have ```ls2003a``` from the ```tests/gsa``` folder
```
options_.relative_irf=1;
irf_calibration;
y(1:4), e_ys, [ -50 50]; //[first year response]
@#for ilag in 21:40
R_obs(@{ilag}), e_ys, [0 6]; //[response after 4th year to 10th year]
@#endfor
end;
```
Thus, you want to restrict the relative IRFs of y and R_obs. But because ```options_.relative_irf``` is generally set, it will also affect the saved results in ```oo_.PosteriorIRF.dsge``` and the displayed IRF-figures. If you wanted the regular, absolute IRFs, there is no way to trigger them. Put differently, the scope/function of the ```relative_irf``` option is larger than just being used in the IRF calibration. Thus, we need to document this clearly.

**Comment by rattoma** [comment]
Right, it will change the behaviour of irfs in all subsequent calls, which can be however reverted?
Can we allow a syntax
`relative_irf=0`
and not only
`relative_irf`
?

**Comment by JohannesPfeifer** [comment]
Maybe a stupid question, but can you have multiple ```irf_calibration``` blocks? In this case, we need to worry about conflicting options.

**Comment by rattoma** [comment]
non rally  `irf_calibration`, but to tackel your worry, there can be first
`irf_calibration`

afterwards

`stoch_simul`

for example, where you would like to plot the levels.

Perhaps, we should set an option for `irf_calibration` that does not alter the global `options_` but only works locally. thus `relative_irf` must be reset to the value it had before entering calibration.
what do you think?

**Comment by JohannesPfeifer** [comment]
@rattoma The problem you describe is a neverending problem. I would not tackle it as it is common and pretty obvious because the figure titles will show you what happened. I was rather worried whether Dynare automatically concatenates several irf_calibration blocks to one joint block as is the case for example with the ```estimated_params``` block. Because in this case, the user could specify conflicting options, trying to have on restriction on relative IRFs and the other on absolute IRFs. If this is not possible, I am satisfied.

**Comment by rattoma** [comment]
So far, only single relative or absolute irf restrictions are allowed, so I think we are OK. thank you
