### ISSUE TITLE
Investigate problem in .mod file

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#857]
http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6577
14 endos in .mod file but preprocessor sees 15

**Comment by MichelJuillard** [comment]
It is exactly as reported in the preprocessor messages:

14 endogenous variables are declared and 1 auxiliary variable is added
because of k(2) [suspicious, probably doesn't use stock on end of
period basis]

there are only 13 equations in the model plus one auxiliary variable
definition

In addition there are two loose "end;" in the *.mod file





Houtan Bastani writes:

> http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6577
> 14 endos in .mod file but preprocessor sees 15
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/DynareTeam/dynare/issues/857

-- 
Michel Juillard

**Comment by houtanb** [comment]
@MichelJuillard thanks for looking into this.

@JohannesPfeifer you can respond to the user with the info @MichelJuillard provided

**Comment by JohannesPfeifer** [comment]
@houtanb Done. @MichelJuillard Thanks. I was stupid and counted a linebreak as two equations.
