### ISSUE TITLE
problem running modfile in octave from draw_prior_density.m

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#868]
http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6627

**Comment by JohannesPfeifer** [comment]
@sebastien-villemot This looks like a bug still present in Octave 4. The reason is a call to 
```
gampdf(1.75000000000000,306.250000000000,0.00571428571428572)
```
In ```gampdf.m``` there are the logical conditions for ```k```:
```
k = (x >= 0) & (a > 0) & (a <= 1) & (b > 0);
  if (isscalar (a) && isscalar (b))
    pdf(k) = (x(k) .^ (a - 1)) ...
              .* exp (- x(k) / b) / gamma (a) / (b ^ a);
  else
    pdf(k) = (x(k) .^ (a(k) - 1)) ...
              .* exp (- x(k) ./ b(k)) ./ gamma (a(k)) ./ (b(k) .^ a(k));
  endif

  k = (x >= 0) & (a > 1) & (b > 0);
  if (isscalar (a) && isscalar (b))
    pdf(k) = exp (- a * log (b) + (a-1) * log (x(k))
                  - x(k) / b - gammaln (a));
  else
    pdf(k) = exp (- a(k) .* log (b(k)) + (a(k)-1) .* log (x(k))
                  - x(k) ./ b(k) - gammaln (a(k)));
  endif
```
We want the second part to execute as a>1. However, due to a missing check whether ```k``` is empty, the first part is executed (and later overwritten) where ```b^a``` evaluates to 0. This does not happen in Dynare as the ```gampdf``` in ```missing/stats``` has an additional check
```if (any (k))```
embedding these statements.

Because it is not a Dynare issue, I would propose to close this ticket.
