### ISSUE TITLE
Fix extended path with varexo_det

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#875]
As noted in #806 ```oo_.exo_simul``` is ```periods``` by ```exo_nbr``` while ```endo_simul``` has periods as the second dimension. This seems to be a problem for e.g. ```extended_path```. See http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6675

**Comment by JohannesPfeifer** [comment]
For reference, the mod-file triggering the crash is 
```
var y, c, k, a, h, b dy;
varexo e, u;
varexo_det e_det;

parameters beta, rho, alpha, delta, theta, psi, tau;

alpha = 0.36;
rho   = 0.95;
tau   = 0.025;
beta  = 0.99;
delta = 0.025;
psi   = 0;
theta = 2.95;

model;
exp(c)*theta*exp(h)^(1+psi)=(1-alpha)*exp(y);
exp(k) = beta*(((exp(b)*exp(c))/(exp(b(+1))*exp(c(+1))))
         *(exp(b(+1))*alpha*exp(y(+1))+(1-delta)*exp(k)));
exp(y) = exp(a)*(exp(k(-1))^alpha)*(exp(h)^(1-alpha));
exp(k) = exp(b)*(exp(y)-exp(c))+(1-delta)*exp(k(-1));
a = rho*a(-1)+tau*b(-1) + e +e_det;
b = tau*a(-1)+rho*b(-1) + u;
dy=(y-0.0775944)/0.0775944*100;
end;

initval;
y = 0.1;
c = -0.2;
h = -1.2;
k =  2.4;
a = 0;
b = 0;
e = 0;
u = 0;
dy=0;
//Sum=c+y;
end;

steady;

shocks;
var e = 0.01^2;
var u = 0.00001;
var e_det;
periods 1:1;
values 0.03;
end;

extended_path( periods=100, solver_periods=200, order=0 ); 
```

**Comment by MichelJuillard** [comment]
I'm not sure that we should allow varexo_det with extended path

**Comment by stepan-a** [comment]
I think we should not, at least for the moment. The meaning is unclear (should we interpret this shock as a surprise, as in the example because it occurs in the first period, or, if the shock is set for future periods, as an expected shock?). Also there is nothing in the extended_path code to handle this case.

My opinion, for the moment, is that the preprocessor should raise an error if the user mixes stochastic and deterministic shocks. I am currently working on this part of the code, and I think that it would be too much work to handle this situation properly.
