### ISSUE TITLE
Fix bug with tests/gsa/ls2003a.mod

### ISSUE THREAD

**Issue by stepan-a** [DynareTeam/dynare#881]
which causes a segmentation fault. See discussion in #880 and commit a7f0366980540d668a4b54bb8517798e1ae4deac.

**Comment by JohannesPfeifer** [comment]
@stepan-a Did this happen in Octave or Matlab? I just ran the file on Matlab and it worked. On Octave however, the problem is that 
```
warning: print.m: epstool binary is not available.
Some output formats are not available.
error: Octave cannot create fig files!
error: called from:
error:   C:\dynare\matlab\dyn_saveas.m at line 52, column 9
```
To make it run, I used 
```
if ~isoctave
dynare_sensitivity(prior_range=0, nodisplay, graph_format=(fig,eps));
else
dynare_sensitivity(prior_range=0, nodisplay, graph_format=(eps));
end
```

**Comment by stepan-a** [comment]
Thanks @JohannesPfeifer. The problem is on Linux/Matlab (I am not sure for Octave). I will give a try to these options.

**Comment by stepan-a** [comment]
I checked that there is no problem on OS X (I think that's why I did not catch the bug yesterday). But on Linux the mod file returns a segmentation fault even with the option ```nograph```. I posted the content of the generated log file [here](https://gist.github.com/stepan-a/4f7925c52b8d59a061a0). @rattoma Do you have any idea?

**Comment by rattoma** [comment]
I think that `nograph` does not work since I forgot to trap plots inside the option ...
So, I think it is a graphical issue: I generate and close a lot of files. Also I use `annotation` and `path` objects, which are two things that perhaps are not so commonly used in other dynare places?
One thing I would check, is to apply the option `graph_format(eps,fig)` also in the `dynare_sensitivity` calls of `ls2003.mod`. Interesting to see if this also triggers fault.

By the way, only saving as `eps` still triggers the fault?

**Comment by rattoma** [comment]
Some major fixes are done in https://github.com/rattoma/dynare/commit/41cebf7e4e0f76f50d4ded96b63d449ea7084991.
If it still does not go, one can at least run it with nograph

**Comment by stepan-a** [comment]
It's working with ```graph_format=(fig)``` and ```nograph``` under Matlab. So the problem concerns the ```eps``` format. With Octave ```eps```format works fine (```nograph``). I do not know why ```eps``` is not working with Matlab, and if the crash is version dependent...

**Comment by rattoma** [comment]
OK with `nograph`, since now no plot is initiated there. 
On the mac it works with `eps` and Matlab.

I think it can be an issues related to the behavior of different platforms when the figure is not visible. With `eps`, we have in `dyn_saveas`, lines 37-39 on for Octave:
`
        if DynareOptions.nodisplay && ispc,
            set(h, 'Visible','on');
        end
`
could you try in linux setting the plot visible also in Matlab `&&` Linux?

**Comment by rattoma** [comment]
I don't think it will work since otherwise should provide the fault always. Anyhow, I noted a different behavior on different platforms of using
`figure(fig_handle)`
to make `fig_handle` the current figure. 
On mac (presumably also on linux) this makes the figure visible even if it was not. On PC the figure remains not visible.
To keep figure not visible on mac I had to change the syntax to
`set(0,'currentfigure',fig_handle)`
When you use `eps` with MATLAB, can you tell me the name of the last `eps` figure saved before the crash in the sub-folder
`ls2003a/gsa`
?
thank you

**Comment by rattoma** [comment]
perhaps my last pull request will help...

**Comment by stepan-a** [comment]
So here is the output of ```ls -latr```in ```tests/gsa/ls2003a/gsa```. The last generated eps file is on the last line.

```shell
-rw-r--r-- 1 stepan stepan  413267 Apr 16 09:14 ls2003a_prior.mat
-rw-r--r-- 1 stepan stepan  100418 Apr 16 09:14 ls2003a_prior_stable.eps
-rw-r--r-- 1 stepan stepan  100396 Apr 16 09:14 ls2003a_prior_indeterm.eps
-rw-r--r-- 1 stepan stepan  745255 Apr 16 09:14 ls2003a_prior_calib.eps
-rw-r--r-- 1 stepan stepan  904321 Apr 16 09:15 ls2003a_prior_restrictions.mat
-rw-r--r-- 1 stepan stepan  245671 Apr 16 09:15 ls2003a_prior_irf_calib_y_vs_e_ys_1-4.eps
-rw-r--r-- 1 stepan stepan  460003 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_21.eps
-rw-r--r-- 1 stepan stepan  459506 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_22.eps
-rw-r--r-- 1 stepan stepan  458828 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_23.eps
-rw-r--r-- 1 stepan stepan  458264 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_24.eps
-rw-r--r-- 1 stepan stepan  457767 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_25.eps
-rw-r--r-- 1 stepan stepan  457290 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_26.eps
-rw-r--r-- 1 stepan stepan  456634 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_27.eps
-rw-r--r-- 1 stepan stepan  456197 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_28.eps
-rw-r--r-- 1 stepan stepan 1097346 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_29.eps
-rw-r--r-- 1 stepan stepan 1096595 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_30.eps
-rw-r--r-- 1 stepan stepan 1096176 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_31.eps
-rw-r--r-- 1 stepan stepan 1095592 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_32.eps
-rw-r--r-- 1 stepan stepan 1095343 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_33.eps
-rw-r--r-- 1 stepan stepan 1094831 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_34.eps
-rw-r--r-- 1 stepan stepan  454735 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_35.eps
-rw-r--r-- 1 stepan stepan  454264 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_36.eps
-rw-r--r-- 1 stepan stepan  454103 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_37.eps
-rw-r--r-- 1 stepan stepan  453678 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_38.eps
-rw-r--r-- 1 stepan stepan  453668 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_39.eps
-rw-r--r-- 1 stepan stepan  453507 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_40.eps
-rw-r--r-- 1 stepan stepan  460004 Apr 16 09:15 ls2003a_prior_irf_calib_R_obs_vs_e_ys_ALL.eps
-rw-r--r-- 1 stepan stepan    6027 Apr 16 09:15 ls2003a_prior_irf_restrictions.eps
```
Your last patch (8d679bff6f61896bd708629cfd2fa1f7fe0b0f2a) does not help...

**Comment by rattoma** [comment]
OK. I think the file 
`ls2003a_prior_irf_restrictions.eps`
is corrupted, right?
should be 2MB. 
Might be related to the use of  `facealpha` to allow transparency in a patch 
[this feature is not used elsewhere in dynare, and it is the only fancy thing in that plot]

**Comment by rattoma** [comment]
Yes, that's the issue, see
https://github.com/altmany/export_fig/issues/3

**Comment by stepan-a** [comment]
Okay. Is this thing cosmetic? Can we add a trap for Matlab/Linux in ```gsa/map_calibration.m```?

**Comment by rattoma** [comment]
I am getting rid of `facealpha`

**Comment by rattoma** [comment]
try this please
https://github.com/rattoma/dynare/commit/4e1e7732fddf35352c1459c2a95e62f11e47f5d4
